name: 'dbt_pagila'
version: '1.0.0'
config-version: 2

profile: 'dbt_pagila'

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
test-paths: ["tests"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  dbt_pagila:
    staging:
      +materialized: view
    intermediate:
      +materialized: table
    marts:
      +materialized: table