dbt_pagila:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('DBT_HOST', 'localhost') }}"
      port: "{{ env_var('DBT_PORT', '15432') | int }}"
      user: "{{ env_var('DBT_USER', 'postgres') }}"
      pass: "{{ env_var('DBT_PASSWORD', 'postgres') }}"
      dbname: "{{ env_var('DBT_DBNAME', 'pagila') }}"
      schema: dbt_pagila
      threads: 4